export const PROVINCES_BY_COUNTRY: Record<string, string[]> = {
  Argentina: [
    "Buenos Aires", "CABA", "Catamarca", "Chaco", "Chubut", "Córdoba",
    "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja",
    "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan",
    "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero",
    "Tierra del Fuego", "Tucumán",
  ],
  Uruguay: [
    "Artigas", "Canelones", "Cerro Largo", "Colonia", "Durazno", "Flores",
    "Florida", "Lavalleja", "Maldonado", "Montevideo", "Paysandú", "Río Negro",
    "Rivera", "Rocha", "Salto", "San José", "Soriano", "Tacuarembó",
    "Treinta y Tres",
  ],
  Brasil: [
    "Acre", "Alagoas", "Amapá", "Amazonas", "Bahía", "Ceará",
    "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso",
    "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná",
    "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte",
    "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo",
    "Sergipe", "Tocantins",
  ],
  Chile: [
    "Arica y Parinacota", "Tarapacá", "Antofagasta", "Atacama", "Coquimbo",
    "Valparaíso", "Metropolitana", "O'Higgins", "Maule", "Ñuble", "Biobío",
    "La Araucanía", "Los Ríos", "Los Lagos", "Aysén", "Magallanes",
  ],
  Paraguay: [
    "Alto Paraguay", "Alto Paraná", "Amambay", "Asunción", "Boquerón",
    "Caaguazú", "Caazapá", "Canindeyú", "Central", "Concepción", "Cordillera",
    "Guairá", "Itapúa", "Misiones", "Ñeembucú", "Paraguarí", "Presidente Hayes",
    "San Pedro",
  ],
  Bolivia: [
    "Beni", "Chuquisaca", "Cochabamba", "La Paz", "Oruro", "Pando",
    "Potosí", "Santa Cruz", "Tarija",
  ],
  Perú: [
    "Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca",
    "Callao", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín",
    "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua",
    "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali",
  ],
  Colombia: [
    "Amazonas", "Antioquia", "Arauca", "Atlántico", "Bogotá D.C.", "Bolívar",
    "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó",
    "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira",
    "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo",
    "Quindío", "Risaralda", "San Andrés y Providencia", "Santander", "Sucre",
    "Tolima", "Valle del Cauca", "Vaupés", "Vichada",
  ],
  Venezuela: [
    "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar",
    "Carabobo", "Cojedes", "Delta Amacuro", "Distrito Capital", "Falcón",
    "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta",
    "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy",
    "Zulia",
  ],
  Ecuador: [
    "Azuay", "Bolívar", "Cañar", "Carchi", "Chimborazo", "Cotopaxi",
    "El Oro", "Esmeraldas", "Galápagos", "Guayas", "Imbabura", "Loja",
    "Los Ríos", "Manabí", "Morona Santiago", "Napo", "Orellana", "Pastaza",
    "Pichincha", "Santa Elena", "Santo Domingo", "Sucumbíos", "Tungurahua",
    "Zamora Chinchipe",
  ],
  México: [
    "Aguascalientes", "Baja California", "Baja California Sur", "Campeche",
    "Chiapas", "Chihuahua", "Ciudad de México", "Coahuila", "Colima",
    "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo",
    "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca",
    "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa",
    "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán",
    "Zacatecas",
  ],
  Cuba: [
    "Artemisa", "Camagüey", "Ciego de Ávila", "Cienfuegos", "Granma",
    "Guantánamo", "Holguín", "Isla de la Juventud", "La Habana",
    "Las Tunas", "Matanzas", "Mayabeque", "Pinar del Río", "Sancti Spíritus",
    "Santiago de Cuba", "Villa Clara",
  ],
  "República Dominicana": [
    "Azua", "Bahoruco", "Barahona", "Dajabón", "Distrito Nacional",
    "Duarte", "El Seibo", "Elías Piña", "Espaillat", "Hato Mayor",
    "Hermanas Mirabal", "Independencia", "La Altagracia", "La Romana",
    "La Vega", "María Trinidad Sánchez", "Monseñor Nouel", "Monte Cristi",
    "Monte Plata", "Pedernales", "Peravia", "Puerto Plata", "Samaná",
    "San Cristóbal", "San José de Ocoa", "San Juan", "San Pedro de Macorís",
    "Sánchez Ramírez", "Santiago", "Santiago Rodríguez", "Santo Domingo",
    "Valverde",
  ],
  Guatemala: [
    "Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula",
    "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal",
    "Jalapa", "Jutiapa", "Petén", "Quetzaltenango", "Quiché", "Retalhuleu",
    "Sacatepéquez", "San Marcos", "Santa Rosa", "Sololá", "Suchitepéquez",
    "Totonicapán", "Zacapa",
  ],
  "Costa Rica": [
    "Alajuela", "Cartago", "Guanacaste", "Heredia", "Limón", "Puntarenas",
    "San José",
  ],
  Panamá: [
    "Bocas del Toro", "Chiriquí", "Coclé", "Colón", "Darién", "Emberá",
    "Guna Yala", "Herrera", "Los Santos", "Ngäbe-Buglé", "Panamá",
    "Panamá Oeste", "Veraguas",
  ],
  España: [
    "Álava", "Albacete", "Alicante", "Almería", "Asturias", "Ávila",
    "Badajoz", "Barcelona", "Burgos", "Cáceres", "Cádiz", "Cantabria",
    "Castellón", "Ceuta", "Ciudad Real", "Córdoba", "Cuenca", "Girona",
    "Granada", "Guadalajara", "Guipúzcoa", "Huelva", "Huesca", "Islas Baleares",
    "Jaén", "La Rioja", "Las Palmas", "León", "Lleida", "Lugo", "Madrid",
    "Málaga", "Melilla", "Murcia", "Navarra", "Ourense", "Palencia",
    "Pontevedra", "Salamanca", "Santa Cruz de Tenerife", "Segovia", "Sevilla",
    "Soria", "Tarragona", "Teruel", "Toledo", "Valencia", "Valladolid",
    "Vizcaya", "Zamora", "Zaragoza",
  ],
  "Estados Unidos": [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
    "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
    "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York",
    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "Washington D.C.", "West Virginia", "Wisconsin", "Wyoming",
  ],
  Canadá: [
    "Alberta", "British Columbia", "Manitoba", "New Brunswick",
    "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia",
    "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan",
    "Yukon",
  ],
  "Reino Unido": [
    "Escocia", "Gales", "Inglaterra", "Irlanda del Norte",
  ],
  Alemania: [
    "Baden-Württemberg", "Baviera", "Berlín", "Brandeburgo", "Bremen",
    "Hamburgo", "Hesse", "Mecklemburgo-Pomerania Occidental", "Baja Sajonia",
    "Renania del Norte-Westfalia", "Renania-Palatinado", "Sarre",
    "Sajonia", "Sajonia-Anhalt", "Schleswig-Holstein", "Turingia",
  ],
  Francia: [
    "Auvernia-Ródano-Alpes", "Borgoña-Franco Condado", "Bretaña",
    "Centro-Valle del Loira", "Córcega", "Franco Condado", "Gran Este",
    "Guadalupe", "Guyana Francesa", "Haute-de-France", "Île-de-France",
    "Martinica", "Mayotte", "Normandía", "Nueva Aquitania",
    "Occitania", "Países del Loira", "Provenza-Alpes-Costa Azul",
    "Reunión",
  ],
  Italia: [
    "Abruzos", "Basilicata", "Calabria", "Campania", "Emilia-Romaña",
    "Friuli-Venecia Julia", "Lacio", "Liguria", "Lombardía", "Marcas",
    "Molise", "Piamonte", "Apulia", "Cerdeña", "Sicilia", "Toscana",
    "Trentino-Alto Adigio", "Umbría", "Valle de Aosta", "Véneto",
  ],
  Portugal: [
    "Aveiro", "Beja", "Braga", "Braganza", "Castelo Branco", "Coímbra",
    "Évora", "Faro", "Guarda", "Leiría", "Lisboa", "Portalegre", "Porto",
    "Santarém", "Setúbal", "Viana do Castelo", "Vila Real", "Viseu",
    "Azores", "Madeira",
  ],
  China: [
    "Anhui", "Beijing", "Chongqing", "Fujian", "Gansu", "Guangdong",
    "Guangxi", "Guizhou", "Hainan", "Hebei", "Heilongjiang", "Henan",
    "Hong Kong", "Hubei", "Hunan", "Jiangsu", "Jiangxi", "Jilin",
    "Liaoning", "Macao", "Mongolia Interior", "Ningxia", "Qinghai",
    "Shaanxi", "Shandong", "Shanghai", "Shanxi", "Sichuan", "Tianjin",
    "Tíbet", "Xinjiang", "Yunnan", "Zhejiang",
  ],
  Japón: [
    "Aichi", "Akita", "Aomori", "Chiba", "Ehime", "Fukui", "Fukuoka",
    "Fukushima", "Gifu", "Gunma", "Hiroshima", "Hokkaido", "Hyogo",
    "Ibaraki", "Ishikawa", "Iwate", "Kagawa", "Kagoshima", "Kanagawa",
    "Kochi", "Kumamoto", "Kyoto", "Mie", "Miyagi", "Miyazaki", "Nagano",
    "Nagasaki", "Nara", "Niigata", "Oita", "Okayama", "Okinawa", "Osaka",
    "Saga", "Saitama", "Shiga", "Shimane", "Shizuoka", "Tochigi",
    "Tokushima", "Tokio", "Tottori", "Toyama", "Wakayama", "Yamagata",
    "Yamaguchi", "Yamanashi",
  ],
  "Corea del Sur": [
    "Busan", "Chungcheong del Norte", "Chungcheong del Sur", "Daegu",
    "Daejeon", "Gangwon", "Gwangju", "Gyeonggi", "Gyeongsang del Norte",
    "Gyeongsang del Sur", "Incheon", "Jeju", "Jeolla del Norte",
    "Jeolla del Sur", "Sejong", "Seúl", "Ulsan",
  ],
  India: [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
    "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
    "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
    "Meghalaya", "Mizoram", "Nagaland", "Nueva Delhi", "Odisha", "Punjab",
    "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
    "Uttar Pradesh", "Uttarakhand", "Bengala Occidental",
  ],
  Australia: [
    "Australian Capital Territory", "New South Wales", "Northern Territory",
    "Queensland", "South Australia", "Tasmania", "Victoria",
    "Western Australia",
  ],
  Sudáfrica: [
    "Ciudad del Cabo Occidental", "Estado Libre", "Gauteng", "KwaZulu-Natal",
    "Limpopo", "Mpumalanga", "Noroeste", "Ciudad del Cabo Oriental",
    "Ciudad del Cabo del Norte",
  ],
  Nigeria: [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa",
    "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti",
    "Enugu", "FCT Abuja", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano",
    "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger",
    "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto",
    "Taraba", "Yobe", "Zamfara",
  ],
  Marruecos: [
    "Béni Mellal-Khénifra", "Casablanca-Settat", "Drâa-Tafilalet",
    "Fez-Meknés", "Guelmim-Oued Noun", "Laâyoune-Sakia El Hamra",
    "Marrakech-Safi", "Oriental", "Rabat-Salé-Kénitra",
    "Souss-Massa", "Tánger-Tetuán-Al Hoceima",
  ],
  Rusia: [
    "Adiguesia", "Altái (república)", "Altái (krai)", "Amur", "Arcángel",
    "Astracán", "Bashkortostán", "Belgorod", "Briansk", "Buriatia",
    "Chechenia", "Chelíabinsk", "Chukotka", "Chuvasia", "Daguestán",
    "Ingushetia", "Irkutsk", "Ivánovo", "Kabardino-Balkaria",
    "Kaliningrado", "Kalmukia", "Kaluga", "Kamchatka", "Karacháyevo-Cherkesia",
    "Karelia", "Kémerovo", "Jabárovsk", "Jakutia", "Jantia-Mansisk",
    "Kirov", "Komi", "Kostromá", "Krasnodar", "Krasnoyarsk", "Kurgan",
    "Kursk", "Leningrado", "Lipetsk", "Magadán", "Mari El", "Mordovia",
    "Moscú (ciudad)", "Moscú (óblast)", "Múrmansk", "Nenetsia",
    "Nizhni Nóvgorod", "Novgorod", "Novosibirsk", "Omsk", "Oremburgo",
    "Oriol", "Penza", "Perm", "Primorie", "Pskov", "Rostov",
    "Riazán", "Sajalín", "Samara", "San Petersburgo", "Sarátov",
    "Severnaya Osetia", "Smolensk", "Tambov", "Tartaristán", "Tiumén",
    "Tomsk", "Tula", "Tuvá", "Tver", "Udmurtia", "Uliánovsk",
    "Vladimir", "Volgogrado", "Vologda", "Vorónezh", "Yamalia",
    "Yaroslavl", "Zabaikalie",
  ],
};
